[package]
name = "rhai-net"
version = "0.0.1"
edition = "2021"
authors = ["Dan Killinger <git@dank.anonaddy.com>"]
repository = "https://github.com/rhaiscript/rhai-net"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Networking package for Rhai"
keywords = ["scripting", "scripting-language", "embedded", "rhai", "networking"]
categories = ["embedded"]

[features]
default = []
metadata = ["rhai/metadata"] # doc generation
no_index = []                # support `no_index` builds of rhai

[dependencies]
rhai = { version = ">=1.9" }

[build-dependencies]
rhai = { version = ">=1.9" }
serde_json = "1.0.82"
serde = "1.0.140"

# NOTE: Need to manually specify `metadata` feature for local `cargo doc`.
[package.metadata.docs.rs]
features = ["metadata"]
